# Deploy to Vercel
publish-dir: dist/public

# Build settings
[build]
  command = "npm run build"
  publish = "dist/public"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200